---

#
# example ansible playbook file that expect vagrant provision to run
# http://people.redhat.com/mskinner/rhug/q2.2017/Ansible-Hands-on-Introduction.pdf p23
# https://www.vagrantup.com/docs/provisioning/ansible_intro.html
#
# yaml quirky: 
# --- means start of doc
# ... means end of doc (but often not seen)
# like python, space matter!  it dictates the hierarchy
#    but the "-" to define list has to stick out for visibility.  this make shifting block level a real PITA  !!!! :( 
#    Not sure when need to use "-" and when don't.  Best to use 4 space tab even for "-" and the next/prev block
#    especially when the "when" clause is at the end of the block!!
# vi use
# : set shiftwidth=2 tabstop=4 expandtab list nu ft=ruby
# : retab 
# : syntax on 
# -*- mode: ruby -*-
# vi: set ft=ruby :


## Ansible Wisdom (for now)
## - the way how OS platform/version is handled, the syntax needed to detect them
##   and the number of things that are still platform specific 
##    + (yum vs apt, 
##    + EPEL vs ??, 
##    + yum specific argument that is not supported in package module
##    + package name is that specific to platform (eg kernel-header vs linux-header)
##   it is art to separate out OS specific stuff at the right time on in the hierarchy.
##   Cuz, the anoying thing is that the important code of logic flow may need to be split into two files or two blocks :(
##   On the flip side, the "when: ansible_os_family == 'Debian' is tested at the bottom, easy to miss!!


## instead of yum or apt, should use package module to be platform independent
## http://docs.ansible.com/ansible/latest/package_module.html

#- hosts: ansible_os_family == "RedHat" # this don't work.  
- hosts: all
  become: true  # sudo, default to root
  roles:
    #- role: PeterMosmans.virtualbox-guest # adapted from PeterMosmans.virtualbox-guest
    - role: virtualbox-guest # adapted from PeterMosmans.virtualbox-guest
      # previously ran ansible-galaxy install PeterMosmans.virtualbox-guest to get a role in ~/.ansible/roles
      # https://galaxy.ansible.com/PeterMosmans/virtualbox-guest/
      # cp whole dir to here to adapt code to work in centos
  tasks:
    # next block is platform neutral
    - block:
      - name: ensure ntpd is at the latest version
        package: 
          name:  ntp 
          state: latest
        notify:
          - restart ntpd
      - name: latest zsh is present # the alt syntax for yum/apt is closer to package, and platform neutrality is prefered, even when ther eare lots of name clause.
        package: 
          name: zsh 
          state: latest
        # lxde is not in epel either.  maybe use xfce, which use GDM.  MATE use LightDM and don't want to mess with that.
        # https://github.com/DevOps4Networks/ansible-linux-desktop-role/blob/master/tasks/RedHat.yml
      - name: latest lxde is present
        package: 
          name: lxde 
          state: removed #absent #latest

    # next block for RedHat only
    - block: 
      - name: Install EPEL repo.
        yum:
          name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
          state: latest #present
          # state absent does not ensure it is removed.  
          # present does not revert changes made to file.  think of yum running not ovewriting existing config.
      - name: Import EPEL GPG key.
        rpm_key:
          key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
          state: present
          #validate_certs: no    # still get prompt to accept the key  :(
        # @package-group-name vs @^environment-group-name, see "yum grouplist" and 
        # http://docs.ansible.com/ansible/latest/yum_module.html 
        #when: redhat_desktop == 'xfce'
      - name: Install RedHat X11
        yum: name="@x11" state=present
	### may not have installed xorg-x11-server-... ...common  ...Xvfb 
        ## okay, Xfce and X11 installed, but don't work in virtualbox.  video driver problem
      when: ansible_os_family == "RedHat" # use blok to define this for multiple tasks, but has to be at the end !!  this condition at the end is both a boon and bane!!
    # next block could be platform neutral if figure out the right syntax and/or package name
    # nope, couldn't get the block clause under package to work.  
    #- block:
    #  - name: xfce is present
        #shell: yum --enablerepo=epel -y groupinstall xfce-desktop x11
        #yum: enablerepo=epel name="@Xfce" state=present
    # can I do it this way?    could it be platform neutral??
    #    package: 
    #      - block:
    #          enablerepo=epel 
    #          when ansible_os_family == 'RedHat'
    #      - name: "@Xfce" 
    #      - state: present
    
    - block:
        - name: latest csh is present # trying to exlude this in RedHat.  works.  see result as skip, condition was False.
          apt: pkg=csh state=latest
      when: ansible_os_family == "Debian"  
      # INCLUDE eg, see https://github.com/DevOps4Networks/ansible-linux-desktop-role/blob/master/tasks/main.yml 

  handlers:
    - name: restart ntpd
      service: name=ntpd state=restarted
    # service should be in handler, then even if don't exist, no complain
    # well, nothing will call this block, so maybe why no complains
    - name: stop httpd 
      service:
        name:  http
        state: stopped
 

