---

#
# example ansible playbook file that expect vagrant provision to run
# http://people.redhat.com/mskinner/rhug/q2.2017/Ansible-Hands-on-Introduction.pdf p23
# https://www.vagrantup.com/docs/provisioning/ansible_intro.html
#
# yaml quirky: 
# --- means start of doc
# ... means end of doc (but often not seen)
# like python, space matter!  it dictates the hierarchy
#    but the "-" to define list has to stick out for visibility.  this make shifting block level a real PITA  !!!! :( 
# vi use
# : set shiftwidth=2 tabstop=4

#- hosts: ansible_os_family == "RedHat" # this don't work.  
- hosts: all
  become: true  # sudo, default to root
  tasks:
    - block:
      - name: ensure ntpd is at the latest version
        yum: pkg=ntp state=latest
        notify:
          - restart ntpd
      - name: latest zsh is present # alt syntax, but i like it less, too name "name" clause
        yum: 
          name: zsh 
          state: latest
      when: ansible_os_family == "RedHat" # use blok to define this for multiple tasks, but has to be at the end !! WHY?!
  handlers:
    - name: restart ntpd
      service: name=ntpd state=restarted
    # service should be in handler, then even if don't exist, no complain
    # well, nothing will call this block, so maybe why no complains
    - name: stop httpd 
      service:
        name:  http
        state: stopped
 

